name: Open Issue Workflow

on:
  issues: 
    types: [opened, labeled]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    # Print the whole Github Context to the logs to view more details.
    - name: View the github context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        
    - name: Open new ISSUE on GuillaumeFalourd/poc-github-actions repository
      if: contains(github.event.label.name , 'documentation')
      uses: GuillaumeFalourd/open-issue-action@main
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        repo-owner: GuillaumeFalourd
        repo-name: poc-github-actions
        issue-title: ${{ github.event.issue.title }}
        issue-body: This is a test openning a new ISSUE through the open-issue-action!
        issue-labels: documentation # Not mandatory
        issue-assignees: GuillaumeFalourd # Not mandatory